mdapi/src/objects/TriggerHandler__mdt.object
<CustomObject>
    <description>Defines and controls Trigger Events</description>
    <label>Trigger Handler</label>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is active</description>
        <inlineHelpText>Denotes whether or not this Handler is active</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAfter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for After events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for After events</inlineHelpText>
        <label>After Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBefore__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for Before events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for Before events</inlineHelpText>
        <label>Before Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for Delete events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for Delete events</inlineHelpText>
        <label>Delete Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for Insert events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for Insert events</inlineHelpText>
        <label>Insert Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUndelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for Undelete events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for Undelete events</inlineHelpText>
        <label>Undelete Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this Handler is enabled for Update events</description>
        <inlineHelpText>Denotes whether or not this Handler is enabled for Update events</inlineHelpText>
        <label>Update Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SObject__c</fullName>
        <description>The SObject that this handler should run on</description>
        <inlineHelpText>The SObject that this handler should run on</inlineHelpText>
        <label>SObject</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>Trigger Handlers</relationshipLabel>
        <relationshipName>TriggerHandlers</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
</CustomObject>

dx-workshop/app/main/default/classes/TriggerEvent.cls
/*
 * @author: anthony@cleanbeach.co
 * @created: 2019/05/02
 * @description: Passes context to TriggerHandlers that are registered with this TriggerEvent
 */

public with sharing class TriggerEvent {
    private List<TriggerHandler__mdt> configs;
    private TriggerOperation operation;

    public TriggerEvent(String sObjectName, TriggerOperation operation) {
        this.operation = operation;

        String operationFilter;
        switch on operation {
            when AFTER_DELETE {
                operationFilter = 'AND IsAfter__c = TRUE AND IsDelete__c = TRUE ';
            } when AFTER_INSERT {
                operationFilter = 'AND IsAfter__c = TRUE AND IsInsert__c = TRUE ';
            } when AFTER_UNDELETE {
                operationFilter = 'AND IsAfter__c = TRUE AND IsUndelete__c = TRUE ';
            } when AFTER_UPDATE {
                operationFilter = 'AND IsAfter__c = TRUE AND IsUpdate__c = TRUE ';
            } when BEFORE_DELETE {
                operationFilter = 'AND IsBefore__c = TRUE AND IsDelete__c = TRUE ';
            } when BEFORE_INSERT {
                operationFilter = 'AND IsBefore__c = TRUE AND IsInsert__c = TRUE ';
            } when BEFORE_UPDATE {
                operationFilter = 'AND IsBefore__c = TRUE AND IsUpdate__c = TRUE ';
            }
        }

        String configLoader = 'SELECT Name FROM TriggerHandler__mdt WHERE '
                + 'IsActive__c = TRUE AND SObject__c = ' + sObjectName + ' '
                + operationFilter
                + 'ORDER BY Priority';

        configs = (List<TriggerHandler__mdt>) Database.query(
                configLoader
        );
    }

    public void dispatch() {
        for (TriggerHandler__mdt config : configs) {
            TriggerHandler handler = (TriggerHandler) Type.forName(config.DeveloperName)
                    .newInstance();
            invokeHandler(handler);
        }
    }

    private void invokeHandler(TriggerHandler handler) {
        switch on operation {
            when AFTER_DELETE {
                handler.afterDelete(Trigger.oldMap);
            } when AFTER_INSERT {
                handler.afterInsert(Trigger.newMap);
            } when AFTER_UNDELETE {
                handler.afterUndelete(Trigger.newMap);
            } when AFTER_UPDATE {
                handler.afterUpdate(Trigger.newMap, Trigger.oldMap);
            } when BEFORE_DELETE {
                handler.beforeDelete(Trigger.oldMap);
            } when BEFORE_INSERT {
                handler.beforeInsert(Trigger.new);
            } when BEFORE_UPDATE {
                handler.beforeUpdate(Trigger.newMap, Trigger.oldMap);
            }
        }
    }
}